name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Srinivas"
      - uses: skitionek/notify-microsoft-teams@master
        if:  ${{ success() }}
        with:
          webhook_url: ${{ secrets.MS_WEB_HOOK }}
          job: ${{ toJson(job) }}
